// <auto-generated />
namespace Financeiro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class tabelasIniciais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tabelasIniciais));
        
        string IMigrationMetadata.Id
        {
            get { return "202002060015386_tabelasIniciais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
